#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'maxScore' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER m
#

def maxScore(a, m):
    
    # sort list
    a.sort()
    
    # number of full segments
    segments = len(a) // m - 1
    
    # counters
    i = 1
    j = 0
    
    # arrangement scoring
    score = 0
    productSum = 0
    
    # find full segments
    while i <= segments:
        while j < m:
            productSum += a[0]
            a.pop(0)
            j += 1
        score += i * (productSum)
        productSum = 0
        j = 0
        i += 1
    
    # find last segment
    for x in a:
        productSum += int(x)
    score += (segments + 1) * productSum
    
    
    return score % (10 ** 9 + 7)
                      

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    a = list(map(int, input().rstrip().split()))

    ans = maxScore(a, m)

    fptr.write(str(ans) + '\n')

    fptr.close()
